### ISSUE TITLE
radio button problem i did by following the link--->https://www.npmjs.com/package/nativescript-radiobutton

### ISSUE THREAD

**Issue by radhakrishnan0404** [bradmartin/nativescript-checkbox#47]
ns-renderer: ERROR BOOTSTRAPPING ANGULAR
 ns-renderer: Could not load view for: RadioGroup.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/
     com.tns.Module.resolvePathHelper(Module.java:146)
     com.tns.Module.resolvePath(Module.java:55)
     com.tns.Runtime.callJSMethodNative(Native Method)
     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
     com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
     com.tns.Runtime.callJSMethod(Runtime.java:890)
     com.tns.Runtime.callJSMethod(Runtime.java:874)
     com.tns.Runtime.callJSMethod(Runtime.java:866)
     com.tns.gen.android.app.Application_ActivityLifecycleCallbacks.onActivityResumed(Application_ActivityLifecycleCallbacks.java:24)
     android.app.Application.dispatchActivityResumed(Application.java:216)
     android.app.Activity.onResume(Activity.java:1251)
     android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
     android.app.Activity.performResume(Activity.java:6766)
     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
     android.app.ActivityThread.-wrap12(ActivityThread.java)
     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
     android.os.Handler.dispatchMessage(Handler.java:102)
     android.os.Looper.loop(Looper.java:154)
     android.app.ActivityThread.main(ActivityThread.java:6077)
     java.lang.reflect.Method.invoke(Native Method)
     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

 TypeError: Could not load view for: RadioGroup.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/
     com.tns.Module.resolvePathHelper(Module.java:146)
     com.tns.Module.resolvePath(Module.java:55)
     com.tns.Runtime.callJSMethodNative(Native Method)
     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
     com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
     com.tns.Runtime.callJSMethod(Runtime.java:890)
     com.tns.Runtime.callJSMethod(Runtime.java:874)
     com.tns.Runtime.callJSMethod(Runtime.java:866)
     com.tns.gen.android.app.Application_ActivityLifecycleCallbacks.onActivityResumed(Application_ActivityLifecycleCallbacks.java:24)
     android.app.Application.dispatchActivityResumed(Application.java:216)
     android.app.Activity.onResume(Activity.java:1251)
     android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
     android.app.Activity.performResume(Activity.java:6766)
     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2713)
     android.app.ActivityThread.-wrap12(ActivityThread.java)
     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
     android.os.Handler.dispatchMessage(Handler.java:102)
     android.os.Looper.loop(Looper.java:154)
     android.app.ActivityThread.main(ActivityThread.java:6077)
     java.lang.reflect.Method.invoke(Native Method)
     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     at Object.getViewClass (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/nativescript-angular/element-registry.js:29:15)
     at ViewUtil.createView (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/nativescript-angular/view-util.js:122:44)
     at NativeScriptRenderer.createElement (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/nativescript-angular/renderer.js:104:30)
     at DebugRenderer2.createElement (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.j
 s:13284:49)
     at createElement (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:9362:27)
     at createViewNodes (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:12051:44)
     at callViewAction (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:12537:13)
     at execComponentViewsAction (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:12446:13)
     at createViewNodes (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:12120:5)
     at createRootView (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:11998:5)
     at callWithDebugContext (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:13213:42)
     at Object.debugCreateRootView [as createRootView] (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:12673:12)
     at ComponentFactory_.create (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:9919:46)
     at ComponentFactoryBoundToModule.create (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:3455:29)
     at ApplicationRef_.bootstrap (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:5039:57)

**Comment by bradmartin** [comment]
This is your error: TypeError: Could not load view for: RadioGroup.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/

Can you paste your package.json and try updating your packages and rebuilding the application. It looks like your checkbox plugin is not the latest version for NS 3+ because that module being called is not in NS3+ it's for NS2.5.

**Comment by radhakrishnan0404** [comment]
@bradmartin very thanks i have an issue i want to transfer input textfield from one component to another component textfield using @injectable() can you guide me
this is my screen 1
![simulator screen shot 21-jun-2017 6 14 13 pm](https://user-images.githubusercontent.com/29449293/27384784-d86d3100-56ad-11e7-882c-386db2c28792.png)
this is my screen 2
![simulator screen shot 21-jun-2017 6 17 33 pm](https://user-images.githubusercontent.com/29449293/27384836-00087ada-56ae-11e7-9af2-f640d945b2fb.png)
  
from screen 2 text value to screen 1 any text field

**Comment by bradmartin** [comment]
Please ask this on the forum: https://discourse.nativescript.org/ - the checkbox repo is not the place for the input question.
